site_name: Dani Garcia Test
site_url: https://www.danigarcia-sec.xyz

theme:
  name: material
  language: es
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Inicio: index.md
  - Sobre m√≠: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

plugins:
  - search


